In [1]:
import numpy as np
import pandas as pd

# Exercise 1
arr1 = np.arange(1, 11).reshape(2, 5)
print("Exercise 1:")
print(arr1)

Exercise 1:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [2]:
# Exercise 2
arr2 = np.arange(1, 21)
extracted_elements = arr2[5:16]
print("\nExercise 2:")
print(extracted_elements)



Exercise 2:
[ 6  7  8  9 10 11 12 13 14 15 16]


In [3]:
# Exercise 3
series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
series['pears'] = 4
print("\nExercise 3:")
print(series)



Exercise 3:
apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [4]:
# Exercise 4
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hank', 'Ivy', 'Jack'],
    'age': [25, 30, 35, 40, 22, 28, 33, 45, 27, 50],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'M', 'F', 'M']
}
df = pd.DataFrame(data)
print("\nExercise 4:")
print(df)



Exercise 4:
      name  age gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   35      M
3    David   40      M
4      Eve   22      F
5    Frank   28      M
6    Grace   33      F
7     Hank   45      M
8      Ivy   27      F
9     Jack   50      M


In [5]:
# Exercise 5
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print("\nExercise 5:")
print(df)



Exercise 5:
      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
4      Eve   22      F     Manager
5    Frank   28      M     Analyst
6    Grace   33      F  Programmer
7     Hank   45      M     Manager
8      Ivy   27      F     Analyst
9     Jack   50      M  Programmer


In [6]:
# Exercise 6
filtered_df = df[df['age'] >= 30]
print("\nExercise 6:")
print(filtered_df)



Exercise 6:
      name  age gender  occupation
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
6    Grace   33      F  Programmer
7     Hank   45      M     Manager
9     Jack   50      M  Programmer


In [7]:
# Exercise 7
csv_filename = "dataframe.csv"
df.to_csv(csv_filename, index=False)
df_read = pd.read_csv(csv_filename)
print("\nExercise 7:")
print(df_read)



Exercise 7:
      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
4      Eve   22      F     Manager
5    Frank   28      M     Analyst
6    Grace   33      F  Programmer
7     Hank   45      M     Manager
8      Ivy   27      F     Analyst
9     Jack   50      M  Programmer
